### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by Kickball** [macfanatic/SprintApp#46]
Does SprintApp support the use of a MYSQL server over a postgresql database?

If so, how would it be setup?

**Comment by macfanatic** [comment]
Most of the app would work with MYSQL, but the main problems I think you would run into are in running some of the reports.

As this isn't actively maintained and it's an older project at this point anyway, I couldn't really tell you for sure since I never ran it on anything other than Postgresql on Heroku.

The only way to try would be to point your `config/database.yml` to a postgresl adapter and database, and update the `Gemfile` to include the needed gems to support that connection. Then seed the database and boot the Rails app and test it out.

**Comment by Kickball** [comment]
Thanks.

Also I missed the part about the project being deprecated, my bad.

Thanks,
Kickball
